// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppPoD
NumericVector cppPoD(NumericVector titer, double pmax, double et50, double slope, bool adjustTiters, double adjustFrom, double adjustTo);
RcppExport SEXP _PoDBAY_cppPoD(SEXP titerSEXP, SEXP pmaxSEXP, SEXP et50SEXP, SEXP slopeSEXP, SEXP adjustTitersSEXP, SEXP adjustFromSEXP, SEXP adjustToSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type titer(titerSEXP);
    Rcpp::traits::input_parameter< double >::type pmax(pmaxSEXP);
    Rcpp::traits::input_parameter< double >::type et50(et50SEXP);
    Rcpp::traits::input_parameter< double >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< bool >::type adjustTiters(adjustTitersSEXP);
    Rcpp::traits::input_parameter< double >::type adjustFrom(adjustFromSEXP);
    Rcpp::traits::input_parameter< double >::type adjustTo(adjustToSEXP);
    rcpp_result_gen = Rcpp::wrap(cppPoD(titer, pmax, et50, slope, adjustTiters, adjustFrom, adjustTo));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PoDBAY_cppPoD", (DL_FUNC) &_PoDBAY_cppPoD, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_PoDBAY(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
